version: "3.9"
services:
  go-backend:
    container_name: go-app  # Đặt tên container cho ứng dụng Go
    build:
      context: .
      args:
        - JWT_SIGNER_KEY
        - DB_HOST
        - DB_PORT
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
#    environment:
#      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
    depends_on:
      - my-mysql
  my-mysql:
    container_name: go_mysql-db  # Đặt tên container cho MySQL
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Bạn cần đặt biến môi trường này
      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Lưu trữ dữ liệu database bền vững
volumes:
  db_data: